"""Add models for InventoryItem, Customer, Staff, and Transaction

Revision ID: 73a67bf3ed9f
Revises: 67dbb5b455f7
Create Date: 2024-07-18 23:49:48.736613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a67bf3ed9f'
down_revision = '67dbb5b455f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('_password', sa.String(length=128), nullable=False))
    op.alter_column('customers', 'username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.drop_column('customers', 'contact')
    op.drop_column('customers', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('contact', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('customers', 'email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('customers', 'username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('customers', '_password')
    # ### end Alembic commands ###
