// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOhliGSn5camkyqgsOy0XgCk7HC64lKoc',
    appId: '1:520916061327:web:3dd630deff57f83d6cb4fa',
    messagingSenderId: '520916061327',
    projectId: 'myapp-4e8de',
    authDomain: 'myapp-4e8de.firebaseapp.com',
    databaseURL: 'https://myapp-4e8de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myapp-4e8de.appspot.com',
    measurementId: 'G-9Z8XEHK235',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCECpQxKZ5dYaetF0YJRTCIURvPkiAwQPo',
    appId: '1:520916061327:android:f270232f1e9f3f516cb4fa',
    messagingSenderId: '520916061327',
    projectId: 'myapp-4e8de',
    databaseURL: 'https://myapp-4e8de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myapp-4e8de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG1WxaDKLB9maNQwalnw-dqTxX4mYM2-I',
    appId: '1:520916061327:ios:31db2403efaa64d56cb4fa',
    messagingSenderId: '520916061327',
    projectId: 'myapp-4e8de',
    databaseURL: 'https://myapp-4e8de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myapp-4e8de.appspot.com',
    iosClientId: '520916061327-j71b12b8v38dil641tukuldrigjuq436.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG1WxaDKLB9maNQwalnw-dqTxX4mYM2-I',
    appId: '1:520916061327:ios:31db2403efaa64d56cb4fa',
    messagingSenderId: '520916061327',
    projectId: 'myapp-4e8de',
    databaseURL: 'https://myapp-4e8de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myapp-4e8de.appspot.com',
    iosClientId: '520916061327-j71b12b8v38dil641tukuldrigjuq436.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOhliGSn5camkyqgsOy0XgCk7HC64lKoc',
    appId: '1:520916061327:web:99a2bf0791eddc926cb4fa',
    messagingSenderId: '520916061327',
    projectId: 'myapp-4e8de',
    authDomain: 'myapp-4e8de.firebaseapp.com',
    databaseURL: 'https://myapp-4e8de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myapp-4e8de.appspot.com',
    measurementId: 'G-EJHERNLZHW',
  );
}
